language: "en"
early_access: true
reviews:
  request_changes_workflow: true
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: true
  path_filters:
    - "!**/*.lockb"
    - "!blocklist"
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "DRAFT"
    drafts: false
    base_branches:
      - "develop"
      - "master"
chat:
  auto_reply: true
